name: Ubuntu build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ issue-1 ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  Ubuntu-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install packages Ubuntu
# Already installed: bison flex fuse3 pkg-config 
      run: |
        sudo apt-get install \
        ronn binutils-dev libarchive-dev libevent-dev libjemalloc-dev \
        libdouble-conversion-dev libiberty-dev liblz4-dev liblzma-dev libssl-dev \
        libboost-context-dev libboost-filesystem-dev libboost-program-options-dev \
        libboost-python-dev libboost-regex-dev libboost-system-dev libboost-thread-dev 

